apiVersion: v1
kind: Pod
metadata:
  name: "ubuntu-{{.Index}}"
  labels:
    app: ubuntu-app
spec:
  containers:
  - image: "ubuntu:18.04"
    command:
      - /bin/bash
      - -c
      - |
        date
        sleep 5
        date
    imagePullPolicy: IfNotPresent
    name: ubuntu-container
  restartPolicy: Never
